package com.pmdgaming5.ballplatformer;

import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.*;
import android.media.*;
import android.os.SystemClock;
import android.view.MotionEvent;
import android.view.View;
import java.util.*;

public final class GameView extends View {
    private static final int LEVELS=32, ENDLESS=33;
    private static final float R=30f;
    private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG), s=new Paint(Paint.ANTI_ALIAS_FLAG);
    private final SharedPreferences prefs;
    private final ArrayList<RectF> solids=new ArrayList<>(), spikes=new ArrayList<>(), springs=new ArrayList<>();
    private final ArrayList<Checkpoint> checkpoints=new ArrayList<>(), gems=new ArrayList<>(), particles=new ArrayList<>(), shots=new ArrayList<>();
    private final ArrayList<Platform> platforms=new ArrayList<>(), enemies=new ArrayList<>();
    private int ui=0,level=1,unlocked,totalGems,levelGems,deaths,bestEndless,endlessScore,skin,theme;
    private boolean muted,endlessMode,bossAlive,lifecyclePaused,grounded,jumpPressed;
    private float x=260,y=650,vx,vy,cameraX,cameraY,worldW,checkpointX=260,checkpointY=650;
    private float bossX,bossY,bossHp,bossMaxHp,bossTimer,segmentCursor,shake;
    private int endlessSeed,leftId=-1,rightId=-1,jumpId=-1;
    private long groundedAt,jumpUntil,elapsed,lastNs,bossHitAt;
    private final Random rng=new Random(12345);

    public GameView(Context c){super(c);prefs=c.getSharedPreferences("ball_platformer",Context.MODE_PRIVATE);unlocked=clampi(prefs.getInt("unlocked",1),1,LEVELS);totalGems=Math.max(0,prefs.getInt("gems",0));bestEndless=Math.max(0,prefs.getInt("best_endless",0));skin=clampi(prefs.getInt("skin",0),0,2);muted=prefs.getBoolean("muted",false);s.setStyle(Paint.Style.STROKE);setFocusable(true);setLayerType(View.LAYER_TYPE_HARDWARE,null);lastNs=System.nanoTime();}
    public void resumeGame(){lifecyclePaused=false;lastNs=System.nanoTime();invalidate();}
    public void pauseForLifecycle(){lifecyclePaused=true;Audio.stopAll();clearPointers();}
    @Override protected void onDraw(Canvas c){long n=System.nanoTime();float dt=Math.min(.033f,Math.max(0,(n-lastNs)/1_000_000_000f));lastNs=n;if(!lifecyclePaused&&ui==2)update(dt);render(c);postInvalidateOnAnimation();}

    private void update(float dt){elapsed+=(long)(dt*1000);updatePlatforms(dt);if(endlessMode)ensureEndless();move(dt);for(Enemy e:enemies)if(e.alive)e.update(dt);for(Shot q:shots){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=520*dt;q.life-=dt;}shots.removeIf(q->q.life<=0||q.x<cameraX-700||q.x>cameraX+getWidth()+900);collect();hazards();checkpoints();boss(dt);for(Particle q:particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=520*dt;q.vx*=.985f;}particles.removeIf(q->q.life<=0);if(!endlessMode&&!bossAlive&&x>worldW-180)finish();if(endlessMode)endlessScore=Math.max(endlessScore,(int)((x-260)/7)+levelGems*100);if(endlessScore>bestEndless){bestEndless=endlessScore;save();}camera(dt);}

    private void move(float dt){boolean L=leftId>=0,Rr=rightId>=0; if(L)vx-=1750*dt;if(Rr)vx+=1750*dt;if(!L&&!Rr)vx*=Math.pow(.0012,dt);vx=clamp(vx,-690,690);long now=SystemClock.uptimeMillis();if(jumpPressed){jumpUntil=now+150;jumpPressed=false;}if(now<=jumpUntil&&(grounded||now-groundedAt<130)){vy=-1020;grounded=false;jumpUntil=0;burst(x,y+R,10,0xFFBDEBFF);Audio.play(Audio.JUMP,muted);}if(jumpId<0&&vy<-420)vy+=1700*dt;vy+=2450*dt;vy=clamp(vy,-1180,1500);float ox=x,oy=y;x+=vx*dt;y+=vy*dt;grounded=false;for(RectF q:solids)resolve(q,ox,oy);for(Platform m:platforms){RectF q=m.rect();if(circleRect(x,y,R,q)&&oy+R<=q.top+8&&y+R>=q.top){y=q.top-R;vy=0;grounded=true;groundedAt=now;x+=m.dx;y+=m.dy;}}if(y>1400)respawn();}
    private void resolve(RectF q,float ox,float oy){if(!circleRect(x,y,R,q))return;if(ox+R<=q.left&&x+R>q.left){x=q.left-R;vx=-Math.abs(vx)*.12f;}else if(ox-R>=q.right&&x-R<q.right){x=q.right+R;vx=Math.abs(vx)*.12f;}else if(oy+R<=q.top&&y+R>q.top){y=q.top-R;vy=0;grounded=true;groundedAt=SystemClock.uptimeMillis();}else if(oy-R>=q.bottom&&y-R<q.bottom){y=q.bottom+R;vy=Math.max(0,vy);}}
    private void updatePlatforms(float dt){for(Platform m:platforms){float ox=m.x,oy=m.y;m.t+=dt*m.speed;float z=(float)Math.sin(m.t)*m.range;if(m.axis==0)m.x=m.bx+z;else m.y=m.by+z;m.dx=m.x-ox;m.dy=m.y-oy;}}

    private void collect(){for(Gem g:gems)if(!g.got&&hit(x,y,R,g.x,g.y,g.r)){g.got=true;levelGems++;totalGems++;save();burst(g.x,g.y,12,0xFFFFD54A);Audio.play(Audio.COIN,muted);}}
    private void hazards(){for(RectF q:spikes)if(circleRect(x,y,R,q)){respawn();return;}for(RectF q:springs)if(circleRect(x,y,R,q)&&vy>=0){y=q.top-R;vy=-1320;grounded=false;burst(x,y+R,14,0xFF74E7FF);Audio.play(Audio.SPRING,muted);}for(Shot q:shots)if(hit(x,y,R,q.x,q.y,q.r)){respawn();return;}for(Enemy e:enemies)if(e.alive&&hit(x,y,R,e.x,e.y,e.size*.72f)){long now=SystemClock.uptimeMillis();boolean stomp=vy>0&&y+R<e.y+e.size*.35f&&Math.abs(x-e.x)<e.size*.9f;if(stomp&&now-e.hitAt>250){e.alive=false;vy=-900;burst(e.x,e.y,18,0xFFFFC04A);Audio.play(Audio.COIN,muted);}else if(now-e.hitAt>500){e.hitAt=now;respawn();return;}}}
    private void checkpoints(){for(Checkpoint q:checkpoints)if(!q.active&&Math.abs(x-q.x)<48&&Math.abs(y-q.y)<110){q.active=true;checkpointX=q.x;checkpointY=q.y-60;burst(q.x,q.y-58,16,0xFF7DFFB2);Audio.play(Audio.CHECK,muted);}}

    private void boss(float dt){if(!bossAlive)return;if(bossHp<=0){bossAlive=false;burst(bossX,bossY,55,0xFFFFD166);Audio.play(Audio.WIN,muted);return;}bossTimer+=dt;bossX+=(x-bossX)*Math.min(1,dt*1.15f);bossY=600+(float)Math.sin(bossTimer*2.1)*36;if(bossTimer>1.15){bossTimer=0;float dx=x-bossX,dy=y-bossY,len=Math.max(1,(float)Math.hypot(dx,dy));shots.add(new Shot(bossX,bossY,dx/len*430,dy/len*430,15));Audio.play(Audio.BOSS,muted);}long now=SystemClock.uptimeMillis();if(hit(x,y,R,bossX,bossY,72)&&now-bossHitAt>700)respawn();if(vy>0&&y+R<bossY+22&&y+R>bossY-50&&Math.abs(x-bossX)<82&&now-bossHitAt>450){bossHp-=25;bossHitAt=now;vy=-850;burst(bossX,bossY,20,0xFFFFA95A);Audio.play(Audio.COIN,muted);}}
    private void respawn(){deaths++;x=checkpointX;y=checkpointY;vx=vy=0;shake=.55f;shots.clear();burst(x,y,18,0xFFFF6B6B);Audio.play(Audio.HURT,muted);}
    private void finish(){ui=4;if(level<LEVELS)unlocked=Math.max(unlocked,level+1);save();Audio.stopAll();Audio.play(Audio.WIN,muted);burst(x,y,42,0xFFFFD166);}

    private void ensureEndless(){while(segmentCursor<x+getWidth()*3)genSegment();float cut=cameraX-1000;solids.removeIf(q->q.right<cut);spikes.removeIf(q->q.right<cut);springs.removeIf(q->q.right<cut);platforms.removeIf(q->q.x+q.w<cut);gems.removeIf(q->q.x<cut);enemies.removeIf(q->q.x<cut);}
    private void genSegment(){Random r=new Random(endlessSeed+(long)(segmentCursor*31));float gap=65+r.nextInt(95),w=390+r.nextInt(330),top=720-r.nextInt(180),st=segmentCursor+gap;solids.add(new RectF(st,top,st+w,top+145));if(r.nextFloat()<.70)gems.add(new Gem(st+w*.46f,top-72,r.nextInt()));if(r.nextFloat()<.45)spikes.add(new RectF(st+w*.64f,top-24,st+w*.64f+48,top+18));if(r.nextFloat()<.22)springs.add(new RectF(st+w*.2f,top-27,st+w*.2f+72,top+3));if(r.nextFloat()<.48)enemies.add(new Enemy(st+w*.76f,top-32,r.nextInt(3),95+r.nextInt(70)));if(r.nextFloat()<.30)platforms.add(new Platform(st+w*.34f,top-155,160,25,45+r.nextInt(45),.8f+r.nextFloat()*.8f,r.nextBoolean()?0:1));segmentCursor=st+w;}

    private void startLevel(int id){level=id;endlessMode=false;elapsed=deaths=levelGems=endlessScore=0;bossAlive=false;cameraX=cameraY=0;checkpointX=260;checkpointY=650;x=260;y=650;vx=vy=0;clear();build(id);ui=2;Audio.music(id,muted);}
    private void startEndless(){level=ENDLESS;endlessMode=true;elapsed=deaths=levelGems=endlessScore=0;bossAlive=false;cameraX=cameraY=0;checkpointX=260;checkpointY=650;x=260;y=650;vx=vy=0;segmentCursor=820;endlessSeed=(int)(System.currentTimeMillis()&0x7fffffff);clear();solids.add(new RectF(0,820,820,145));genSegment();ui=2;Audio.music(0,muted);}
    private void clear(){solids.clear();spikes.clear();springs.clear();checkpoints.clear();platforms.clear();gems.clear();enemies.clear();particles.clear();shots.clear();}
    private void build(int id){int world=(id-1)/8,var=(id-1)%8;theme=world;worldW=5900+world*520+var*190;Random r=new Random(id*997);float cur=0;solids.add(new RectF(0,805,820,150));cur=740;for(int i=0;i<18+world;i++){float gap=55+r.nextInt(95),w=360+r.nextInt(300),top=775-(i%3)*55-(var%2)*12;cur+=gap;solids.add(new RectF(cur,top,cur+w,top+145));if(i%2==0)gems.add(new Gem(cur+w*.45f,top-70,i*41));if((i+var)%3==1)spikes.add(new RectF(cur+w*.66f,top-24,cur+w*.66f+48,top+18));if((i+world)%5==2)springs.add(new RectF(cur+w*.2f,top-27,cur+w*.2f+72,top+3));if((i+id)%3!=0)enemies.add(new Enemy(cur+w*.77f,top-32,(i+id)%3,90+(id%5)*14));if(i%4==2)platforms.add(new Platform(cur+w*.32f,top-150,155,24,55+(i%2)*20,.8f+(i%3)*.2f,i%2));if(i==5||i==11)checkpoints.add(new Checkpoint(cur+w*.2f,top));cur+=w;}while(cur<worldW-500){cur+=80;solids.add(new RectF(cur,820,480,140));if(((int)cur/100)%2==0)gems.add(new Gem(cur+215,742,(int)cur));cur+=480;}solids.add(new RectF(worldW-590,560,worldW-270,615));solids.add(new RectF(worldW-270,690,worldW,950));if(id%8==0){bossAlive=true;bossX=worldW-640;bossY=600;bossMaxHp=130+world*40;bossHp=bossMaxHp;}}

    private void render(Canvas c){int w=getWidth(),h=getHeight();if(ui==0)menu(c,w,h);else if(ui==1)select(c,w,h);else if(ui==5)settings(c,w,h);else{world(c,w,h);if(ui==3)pause(c,w,h);if(ui==4)win(c,w,h);}}
    private void world(Canvas c,int w,int h){int top=theme==0?0xFF72D7FF:theme==1?0xFF223B62:theme==2?0xFF45305E:0xFF293844;int bot=theme==0?0xFFB8F28B:theme==1?0xFF6A4F3D:theme==2?0xFF182439:0xFF626E74;p.setShader(new LinearGradient(0,0,0,h,top,bot,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);drawSky(c,w,h);c.save();c.translate(-cameraX,-cameraY);if(shake>.01)c.translate((float)Math.sin(elapsed*.03)*shake*10,(float)Math.cos(elapsed*.02)*shake*10);for(RectF q:solids)drawGround(c,q);for(Platform m:platforms)drawPlatform(c,m);for(RectF q:springs)drawSpring(c,q);for(RectF q:spikes)drawSpike(c,q);for(Checkpoint q:checkpoints)drawFlag(c,q);for(Gem q:gems)if(!q.got)drawStar(c,q);for(Enemy e:enemies)if(e.alive)e.draw(c);for(Shot q:shots)drawShot(c,q);if(bossAlive)drawBoss(c);if(!endlessMode)drawGoal(c);for(Particle q:particles)drawParticle(c,q);drawBall(c);c.restore();hud(c,w,h);controls(c,w,h);}
    private void drawSky(Canvas c,int w,int h){if(theme!=0)return;p.setColor(0x66FFFFFF);for(int i=0;i<5;i++){float cx=(i*260+80)-(cameraX*.08f%1300),cy=95+(i%2)*58;c.drawOval(cx,cy,cx+130,cy+38,p);c.drawOval(cx+45,cy-18,cx+175,cy+38,p);}p.setColor(0xFFFFE37A);c.drawCircle(w-100,95,42,p);}
    private void drawGround(Canvas c,RectF q){p.setColor(theme==0?0xFF6A421F:theme==1?0xFF66503C:theme==2?0xFF283040:0xFF49535A);c.drawRoundRect(q,12,12,p);p.setColor(theme==0?0xFF72C83E:theme==1?0xFF7A9B61:0xFF5C6871);c.drawRoundRect(q.left,q.top,q.right,q.top+18,10,10,p);if(theme==0){p.setColor(0xFF3C9D2B);for(int i=(int)q.left;i<q.right;i+=34){Path z=new Path();z.moveTo(i,q.top+18);z.lineTo(i+8,q.top+4);z.lineTo(i+14,q.top+18);z.close();c.drawPath(z,p);}}p.setColor(0x33301000);for(int i=(int)q.left+30;i<q.right;i+=90)c.drawCircle(i,q.top+58,10,p);}
    private void drawPlatform(Canvas c,Platform m){p.setColor(0xFFB98B5B);c.drawRoundRect(m.rect(),8,8,p);p.setColor(0xFF7D5939);c.drawCircle(m.x+25,m.y+12,3,p);c.drawCircle(m.x+m.w-30,m.y+12,3,p);}
    private void drawSpring(Canvas c,RectF q){p.setColor(0xFF536A72);c.drawRoundRect(q,7,7,p);p.setColor(0xFF5DE0FF);c.drawRect(q.left+5,q.top+4,q.right-5,q.top+9,p);}
    private void drawSpike(Canvas c,RectF q){p.setColor(0xFFE9EDF0);Path z=new Path();z.moveTo(q.left,q.bottom);for(int i=0;i<3;i++){float a=q.left+(i+.5f)*(q.width()/3f);z.lineTo(a,q.top);z.lineTo(q.left+(i+1)*(q.width()/3f),q.bottom);}z.close();c.drawPath(z,p);p.setColor(0xFF6C737A);c.drawRect(q.left,q.bottom-5,q.right,q.bottom,p);}
    private void drawFlag(Canvas c,Checkpoint q){p.setColor(0xFF6B523B);c.drawRect(q.x,q.y-78,q.x+5,q.y,p);p.setColor(q.active?0xFF57E37D:0xFFFF5B5B);Path z=new Path();z.moveTo(q.x+5,q.y-76);z.lineTo(q.x+58,q.y-60);z.lineTo(q.x+5,q.y-44);z.close();c.drawPath(z,p);}
    private void drawStar(Canvas c,Gem g){c.save();c.translate(g.x,g.y);float sc=1+(float)Math.sin((elapsed+g.phase)*.006)*.08f;c.scale(sc,sc);p.setShadowLayer(14,0,0,0x99FFD43B);p.setColor(0xFFFFD43B);Path z=new Path();for(int i=0;i<10;i++){double a=-Math.PI/2+i*Math.PI/5;float rr=i%2==0?18:8;float px=(float)Math.cos(a)*rr,py=(float)Math.sin(a)*rr;if(i==0)z.moveTo(px,py);else z.lineTo(px,py);}z.close();c.drawPath(z,p);p.clearShadowLayer();p.setColor(Color.WHITE);c.drawCircle(-5,-5,3,p);c.restore();}
    private void drawBall(Canvas c){c.save();c.translate(x,y);int base=skin==0?0xFFD63B45:skin==1?0xFFE95BA5:0xFF5FD06A;p.setShader(new RadialGradient(-11,-13,R,new int[]{Color.WHITE,base,base,0xFF6A1620},new float[]{0,.12f,.63f,1},Shader.TileMode.CLAMP));p.setShadowLayer(15,0,10,0x88000000);c.drawCircle(0,0,R,p);p.clearShadowLayer();p.setShader(null);p.setColor(Color.WHITE);c.drawOval(-15,-10,-2,4,p);c.drawOval(3,-10,16,4,p);p.setColor(0xFF24313E);c.drawCircle(-9,-3,4,p);c.drawCircle(9,-3,4,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4);p.setColor(0xFF741725);c.drawArc(-13,2,13,21,12,145,false,p);p.setStyle(Paint.Style.FILL);p.setColor(0xFFFFB6B6);c.drawCircle(-6,10,3,p);c.restore();}
    private void drawShot(Canvas c,Shot q){p.setColor(0xFFFF7043);p.setShadowLayer(12,0,0,0xAAFF7043);c.drawCircle(q.x,q.y,q.r,p);p.clearShadowLayer();}
    private void drawBoss(Canvas c){p.setShadowLayer(24,0,12,0xAA000000);p.setColor(0xFF4E5660);c.drawRoundRect(bossX-76,bossY-76,bossX+76,bossY+76,14,14,p);p.clearShadowLayer();p.setColor(0xFFE73D45);c.drawCircle(bossX-25,bossY-12,16,p);c.drawCircle(bossX+25,bossY-12,16,p);p.setColor(Color.WHITE);c.drawCircle(bossX-25,bossY-12,7,p);c.drawCircle(bossX+25,bossY-12,7,p);p.setColor(0xFF2A2026);c.drawRoundRect(bossX-45,bossY+18,bossX+45,bossY+42,10,10,p);p.setColor(0xFFFFF2DA);for(int i=0;i<7;i++)c.drawRect(bossX-35+i*11,bossY+21,bossX-29+i*11,bossY+39,p);p.setColor(0xFF20252C);c.drawRect(bossX-82,bossY-104,bossX+82,bossY-92,p);p.setColor(0xFF62E37E);c.drawRect(bossX-79,bossY-101,bossX-79+158*(bossHp/bossMaxHp),bossY-95,p);}
    private void drawGoal(Canvas c){p.setColor(0xFF5C4932);c.drawRect(worldW-110,555,worldW-104,650,p);p.setColor(0xFFFF5E62);Path z=new Path();z.moveTo(worldW-104,560);z.lineTo(worldW-44,577);z.lineTo(worldW-104,594);z.close();c.drawPath(z,p);}
    private void drawParticle(Canvas c,Particle q){p.setAlpha((int)(255*Math.max(0,q.life/q.max)));p.setColor(q.color);c.drawCircle(q.x,q.y,q.size,p);p.setAlpha(255);}

    private void hud(Canvas c,int w,int h){p.setColor(0xAA17324A);c.drawRoundRect(18,16,315,70,20,20,p);p.setColor(Color.WHITE);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(20);c.drawText(endlessMode?"ENDLESS  "+endlessScore:"LEVEL  "+level+"   ★ "+levelGems,34,50,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(15);c.drawText(formatTime(elapsed),230,50,p);button(c,w-68,44,64,54,"Ⅱ",0x663A5877);}
    private void controls(Canvas c,int w,int h){float cy=h-78;float bw=Math.max(112,w*.16f),bh=86;button(c,bw*.55f,cy,bw,bh,"‹",0x66324D63);button(c,bw*1.55f,cy,bw,bh,"›",0x66324D63);float jw=Math.max(128,w*.19f);button(c,w-jw*.58f,cy,jw,bh,"↑",0x667DFFB2);}
    private void menu(Canvas c,int w,int h){p.setShader(new LinearGradient(0,0,w,h,0xFF5BC6FF,0xFFB7F28B,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);p.setColor(0xFFFFE67A);c.drawCircle(w-110,92,44,p);drawLogo(c,w/2f,h*.29f,84);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setColor(Color.WHITE);p.setTextSize(48);c.drawText("BALL",w/2f,h*.49f,p);p.setColor(0xFFBFEFFF);p.setTextSize(40);c.drawText("PLATFORMER",w/2f,h*.56f,p);button(c,w/2f,h*.66f,290,72,"PLAY",0xCC2E8DB8);button(c,w/2f,h*.75f,290,66,"LEVEL SELECT",0x88455B67);button(c,w/2f,h*.83f,290,66,"ENDLESS MODE",0x88455B67);button(c,w*.85f,h*.75f,80,62,"⚙",0x88455B67);p.setTypeface(Typeface.DEFAULT);p.setTextSize(13);p.setColor(0xDDFFFFFF);c.drawText("32 levels • bosses • stars • checkpoints • endless",w/2f,h-20,p);p.setTextAlign(Paint.Align.LEFT);}
    private void drawLogo(Canvas c,float xx,float yy,float rr){p.setShader(new RadialGradient(xx-18,yy-22,rr,new int[]{Color.WHITE,0xFFFFB8BD,0xFFD63B45,0xFF7A1822},new float[]{0,.12f,.63f,1},Shader.TileMode.CLAMP));c.drawCircle(xx,yy,rr,p);p.setShader(null);p.setColor(Color.WHITE);c.drawOval(xx-42,yy-28,xx-18,yy-2,p);c.drawOval(xx+10,yy-28,xx+34,yy-2,p);p.setColor(0xFF27313C);c.drawCircle(xx-30,yy-13,6,p);c.drawCircle(xx+22,yy-13,6,p);}
    private void select(Canvas c,int w,int h){p.setColor(0xFF0C2A33);c.drawRect(0,0,w,h,p);p.setColor(Color.WHITE);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(34);c.drawText("SELECT LEVEL",28,52,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(15);p.setColor(0xCCFFFFFF);c.drawText("Unlocked "+unlocked+" / "+LEVELS,30,78,p);float gx=w/8.5f;for(int i=1;i<=LEVELS;i++){int rr=(i-1)/8,cc=(i-1)%8;float px=54+cc*gx,py=124+rr*70;boolean open=i<=unlocked;p.setColor(open?0xFF2E7181:0xFF33404A);c.drawRoundRect(px-40,py-25,px+40,py+25,14,14,p);p.setTextAlign(Paint.Align.CENTER);p.setColor(open?0xFFFFD43B:0xFF77818A);p.setTextSize(21);c.drawText(String.valueOf(i),px,py+7,p);}p.setTextAlign(Paint.Align.LEFT);button(c,w-76,h-48,126,64,"BACK",0x663A5877);}
    private void pause(Canvas c,int w,int h){overlay(c);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(42);p.setColor(Color.WHITE);c.drawText("PAUSED",w/2f,h*.27f,p);button(c,w/2f,h*.50f,240,64,"RESUME",0xCC2E8DB8);button(c,w/2f,h*.63f,240,62,"RESTART",0x663A5877);button(c,w/2f,h*.76f,240,62,"LEVEL SELECT",0x663A5877);p.setTextAlign(Paint.Align.LEFT);}
    private void win(Canvas c,int w,int h){overlay(c);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(40);p.setColor(0xFFFFD43B);c.drawText(endlessMode?"ENDLESS RUN":(level==LEVELS?"WORLD COMPLETE!":"LEVEL COMPLETE!"),w/2f,h*.26f,p);p.setTypeface(Typeface.DEFAULT);p.setColor(Color.WHITE);p.setTextSize(20);if(endlessMode)c.drawText("Best  "+bestEndless+"   Score  "+endlessScore,w/2f,h*.39f,p);else{c.drawText("Time  "+formatTime(elapsed),w/2f,h*.37f,p);c.drawText("Stars  "+starsText(),w/2f,h*.44f,p);}button(c,w/2f,h*.60f,270,66,endlessMode?"RUN AGAIN":(level<LEVELS?"NEXT LEVEL":"PLAY AGAIN"),0xCC2E8DB8);button(c,w/2f,h*.74f,270,62,"LEVEL SELECT",0x663A5877);p.setTextAlign(Paint.Align.LEFT);}
    private void settings(Canvas c,int w,int h){p.setColor(0xFF0C2A33);c.drawRect(0,0,w,h,p);p.setColor(Color.WHITE);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(38);c.drawText("SETTINGS",30,60,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(20);c.drawText("Sound",38,140,p);button(c,230,130,170,58,muted?"OFF":"ON",muted?0x663A5877:0xCC2E8DB8);c.drawText("Ball skin",38,220,p);button(c,230,210,170,58,skin==0?"RED":skin==1?"PINK":"GREEN",0x663A5877);c.drawText("Lifetime stars: "+totalGems,38,295,p);c.drawText("Best endless: "+bestEndless,38,330,p);button(c,230,420,230,62,"BACK",0x663A5877);}
    private String starsText(){int st=1;if(deaths<=3)st++;if(levelGems>=3)st++;StringBuilder b=new StringBuilder();for(int i=0;i<3;i++)b.append(i<st?'★':'☆');return b.toString();}
    private void overlay(Canvas c){p.setColor(0xAA050B13);c.drawRect(0,0,getWidth(),getHeight(),p);}
    private void button(Canvas c,float cx,float cy,float w,float h,String t,int col){p.setColor(col);c.drawRoundRect(cx-w/2,cy-h/2,cx+w/2,cy+h/2,20,20,p);s.setColor(0x88FFFFFF);s.setStrokeWidth(2);c.drawRoundRect(cx-w/2,cy-h/2,cx+w/2,cy+h/2,20,20,s);p.setColor(Color.WHITE);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(Math.min(31,h*.38f));c.drawText(t,cx,cy+h*.13f,p);p.setTextAlign(Paint.Align.LEFT);}

    @Override public boolean onTouchEvent(MotionEvent e){int a=e.getActionMasked();int idx=e.getActionIndex();float tx=e.getX(idx),ty=e.getY(idx);if(ui==0&&a==MotionEvent.ACTION_UP){float cx=getWidth()/2f;if(hitRect(tx,ty,cx,getHeight()*.66f,320,82)){startLevel(unlocked);return true;}if(hitRect(tx,ty,cx,getHeight()*.75f,320,78)){ui=1;return true;}if(hitRect(tx,ty,cx,getHeight()*.83f,320,78)){startEndless();return true;}if(hitRect(tx,ty,getWidth()*.85f,getHeight()*.75f,105,78)){ui=5;return true;}return true;}if(ui==1&&a==MotionEvent.ACTION_UP){float gx=getWidth()/8.5f;for(int i=1;i<=LEVELS;i++){int rr=(i-1)/8,cc=(i-1)%8;float px=54+cc*gx,py=124+rr*70;if(i<=unlocked&&hitRect(tx,ty,px,py,98,64)){startLevel(i);return true;}}if(hitRect(tx,ty,getWidth()-76,getHeight()-48,145,76)){ui=0;return true;}return true;}if(ui==5&&a==MotionEvent.ACTION_UP){if(hitRect(tx,ty,230,130,200,72)){muted=!muted;save();return true;}if(hitRect(tx,ty,230,210,200,72)){skin=(skin+1)%3;save();return true;}if(hitRect(tx,ty,230,420,260,76)){ui=0;return true;}return true;}if(ui==3&&a==MotionEvent.ACTION_UP){if(hitRect(tx,ty,getWidth()/2f,getHeight()*.50f,260,78)){ui=2;Audio.music(endlessMode?0:level,muted);return true;}if(hitRect(tx,ty,getWidth()/2f,getHeight()*.63f,260,76)){if(endlessMode)startEndless();else startLevel(level);return true;}if(hitRect(tx,ty,getWidth()/2f,getHeight()*.76f,260,76)){ui=1;Audio.stopAll();return true;}return true;}if(ui==4&&a==MotionEvent.ACTION_UP){if(hitRect(tx,ty,getWidth()/2f,getHeight()*.60f,290,82)){if(endlessMode)startEndless();else startLevel(level<LEVELS?level+1:1);return true;}if(hitRect(tx,ty,getWidth()/2f,getHeight()*.74f,290,78)){ui=1;return true;}return true;}if(ui==2){if(a==MotionEvent.ACTION_UP&&ty<100&&tx>getWidth()-145){ui=3;Audio.stopAll();return true;}handleGameplayTouch(e);return true;}return true;}

    private void handleGameplayTouch(MotionEvent e){int a=e.getActionMasked(),idx=e.getActionIndex(),id=e.getPointerId(idx);float tx=e.getX(idx),ty=e.getY(idx);boolean down=a==MotionEvent.ACTION_DOWN||a==MotionEvent.ACTION_POINTER_DOWN;boolean up=a==MotionEvent.ACTION_UP||a==MotionEvent.ACTION_POINTER_UP||a==MotionEvent.ACTION_CANCEL;float h=getHeight(),w=getWidth();if(down){if(inLeft(tx,ty,w,h)){leftId=id;return;}if(inRight(tx,ty,w,h)){rightId=id;return;}if(inJump(tx,ty,w,h)){jumpId=id;jumpPressed=true;return;}}if(up){if(id==leftId)leftId=-1;if(id==rightId)rightId=-1;if(id==jumpId){jumpId=-1;return;}}}
    private boolean inLeft(float x,float y,float w,float h){return y>h-155&&x<w*.24f;}
    private boolean inRight(float x,float y,float w,float h){return y>h-155&&x>=w*.24f&&x<w*.48f;}
    private boolean inJump(float x,float y,float w,float h){return y>h-170&&x>w*.73f;}
    private void clearPointers(){leftId=rightId=jumpId=-1;}
    private boolean hitRect(float x,float y,float cx,float cy,float w,float h){return Math.abs(x-cx)<=w/2&&Math.abs(y-cy)<=h/2;}
    private static boolean circleRect(float cx,float cy,float r,RectF q){float nx=clamp(cx,q.left,q.right),ny=clamp(cy,q.top,q.bottom),dx=cx-nx,dy=cy-ny;return dx*dx+dy*dy<=r*r;}
    private static boolean hit(float ax,float ay,float ar,float bx,float by,float br){float dx=ax-bx,dy=ay-by,rr=ar+br;return dx*dx+dy*dy<=rr*rr;}
    private static float clamp(float v,float a,float b){return Math.max(a,Math.min(b,v));}
    private static int clampi(int v,int a,int b){return Math.max(a,Math.min(b,v));}
    private static String formatTime(long ms){return String.format(Locale.US,"%02d:%02d",(ms/1000)/60,(ms/1000)%60);}
    private void burst(float px,float py,int n,int color){for(int i=0;i<n;i++){double a=rng.nextDouble()*Math.PI*2;float sp=50+rng.nextFloat()*300;particles.add(new Particle(px,py,(float)Math.cos(a)*sp,(float)Math.sin(a)*sp-50,2+rng.nextFloat()*5,color,.35f+rng.nextFloat()*.55f));}}
    private void save(){prefs.edit().putInt("unlocked",unlocked).putInt("gems",totalGems).putInt("best_endless",bestEndless).putInt("skin",skin).putBoolean("muted",muted).apply();}

    private static final class Gem{final float x,y,r=17;final int phase;boolean got;Gem(float x,float y,int phase){this.x=x;this.y=y;this.phase=phase;}}
    private static final class Checkpoint{final float x,y;boolean active;Checkpoint(float x,float y){this.x=x;this.y=y;}}
    private static final class Particle{float x,y,vx,vy,size,life,max;final int color;Particle(float x,float y,float vx,float vy,float size,int color,float life){this.x=x;this.y=y;this.vx=vx;this.vy=vy;this.size=size;this.color=color;this.life=life;this.max=life;}}
    private static final class Shot{float x,y,vx,vy,r,life=5;Shot(float x,float y,float vx,float vy,float r){this.x=x;this.y=y;this.vx=vx;this.vy=vy;this.r=r;}}
    private static final class Platform{final float bx,by,w,h,range,speed;float x,y,t,dx,dy;final int axis;Platform(float x,float y,float w,float h,float range,float speed,int axis){bx=this.x=x;by=this.y=y;this.w=w;this.h=h;this.range=range;this.speed=speed;this.axis=axis;}RectF rect(){return new RectF(x,y,x+w,y+h);}}
    private static final class Enemy{float x,y,baseY,speed,t,hitAt;final float min,max,size=42;final int type;int dir=1;boolean alive=true;Enemy(float x,float y,int type,float speed){this.x=x;this.y=y;this.baseY=y;this.type=type;this.speed=speed;min=x-125;max=x+125;}void update(float dt){t+=dt;if(type==0){x+=dir*speed*dt;}else if(type==1){x+=(float)Math.sin(t*2.2)*speed*.55f*dt;y=baseY+(float)Math.sin(t*3.2)*42;}else{x+=dir*speed*dt;y=baseY-(float)Math.abs(Math.sin(t*2.8))*40;}if(x<min||x>max)dir*=-1;}void draw(Canvas c){float z=size/2;p.setShadowLayer(10,0,7,0x66000000);p.setColor(0xFF414A53);c.drawRoundRect(x-z,y-z,x+z,y+z,7,7,p);p.clearShadowLayer();p.setColor(0xFF273038);c.drawRect(x-z+5,y+z-10,x+z-5,y+z-5,p);p.setColor(0xFFFFC857);c.drawCircle(x-10,y-7,8,p);c.drawCircle(x+10,y-7,8,p);p.setColor(Color.BLACK);c.drawCircle(x-10+dir*2,y-7,3,p);c.drawCircle(x+10+dir*2,y-7,3,p);p.setColor(0xFF2A1A1E);c.drawRoundRect(x-17,y+5,x+17,y+18,5,5,p);p.setColor(0xFFFFFFFF);for(int i=0;i<5;i++)c.drawRect(x-13+i*6,y+7,x-10+i*6,y+13,p);}}
    private static final class Audio{static final int JUMP=1,COIN=2,HURT=3,WIN=4,SPRING=5,CHECK=6,BOSS=7;static final int RATE=22050;static volatile boolean musicRun;static Thread musicThread;static void play(int t,boolean mute){if(mute)return;float f=t==JUMP?700:t==COIN?980:t==HURT?180:t==WIN?760:t==SPRING?520:t==CHECK?880:240;float d=t==WIN?.4f:.11f;new Thread(()->tone(f,d,t==HURT?.22f:.15f)).start();}static void tone(float f,float d,float vol){int n=(int)(RATE*d);short[] a=new short[n];for(int i=0;i<n;i++){float z=i/(float)RATE,e=Math.min(1,z*30)*Math.min(1,(d-z)*15);a[i]=(short)(Math.sin(6.28318*f*z)*32767*vol*e);}AudioTrack q=new AudioTrack(AudioManager.STREAM_MUSIC,RATE,AudioFormat.CHANNEL_OUT_MONO,AudioFormat.ENCODING_PCM_16BIT,n*2,AudioTrack.MODE_STATIC);q.write(a,0,a.length);q.play();try{Thread.sleep((long)(d*1000)+20);}catch(Exception ignored){}q.release();}static void music(int lv,boolean mute){stopAll();if(mute)return;musicRun=true;musicThread=new Thread(()->{float[] ns={261.6f,329.6f,392f,523.3f,392f,329.6f,293.7f,349.2f};while(musicRun)for(float f:ns){if(!musicRun)break;tone(f,.12f,.032f);}});musicThread.start();}static void stopAll(){musicRun=false;if(musicThread!=null)musicThread.interrupt();musicThread=null;}}
}