package com.pmdgaming5.ballplatformer;

import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.*;
import android.media.*;
import android.os.SystemClock;
import android.view.MotionEvent;
import android.view.View;
import java.util.*;

public final class GameView extends View {
    private static final int LEVEL_COUNT=24;
    private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG), s=new Paint(Paint.ANTI_ALIAS_FLAG);
    private final SharedPreferences prefs;
    private final Random rng=new Random(7);
    private final ArrayList<RectF> blocks=new ArrayList<>(), spikes=new ArrayList<>(), springs=new ArrayList<>(), checkpoints=new ArrayList<>(), moving=new ArrayList<>();
    private final ArrayList<Gem> gems=new ArrayList<>(), enemies=new ArrayList<>(), shots=new ArrayList<>(), particles=new ArrayList<>();
    private int unlocked,level=1,gemsThis=0,gemsTotal,deaths;
    private boolean muted,paused,lifecyclePaused,left,right,jumpHeld,jumpPressed,won,bossAlive;
    private float x,y,vx,vy,r=28,cameraX,cameraY,worldW,bossX,bossY,bossHp,bossMaxHp,bossTimer,shake;
    private boolean grounded; private long groundedAt,jumpAt,bossHitAt; private long elapsed,lastFrame;
    private int facing=1;
    private final Sfx audio=new Sfx();

    public GameView(Context c){super(c);prefs=c.getSharedPreferences("ball_platformer",0);unlocked=Math.max(1,prefs.getInt("unlocked",1));gemsTotal=prefs.getInt("gems",0);muted=prefs.getBoolean("muted",false);s.setStyle(Paint.Style.STROKE);setFocusable(true);setLayerType(View.LAYER_TYPE_HARDWARE,null);lastFrame=System.nanoTime();}
    public void resumeGame(){lifecyclePaused=false;lastFrame=System.nanoTime();}
    public void pauseForLifecycle(){lifecyclePaused=true;audio.stop();}
    @Override protected void onDraw(Canvas c){long now=System.nanoTime();float dt=Math.min(.033f,(now-lastFrame)/1e9f);lastFrame=now;if(!lifecyclePaused&&screen()==2)tick(dt);render(c);postInvalidateOnAnimation();}
    // 0 menu, 1 select, 2 play, 3 pause, 4 win, 5 settings
    private int ui=0;
    private int screen(){return ui;}
    private void startLevel(int n){level=Math.max(1,Math.min(LEVEL_COUNT,n));ui=2;elapsed=0;deaths=0;gemsThis=0;won=false;paused=false;bossAlive=false;cameraX=cameraY=0;shake=0;left=right=jumpHeld=jumpPressed=false;blocks.clear();spikes.clear();springs.clear();checkpoints.clear();moving.clear();gems.clear();enemies.clear();shots.clear();particles.clear();LevelFactory.make(this,level);x=270;y=650;vx=vy=0;grounded=false;groundedAt=0;jumpAt=0;audio.music(level,muted);}
    private void tick(float dt){elapsed+=(long)(dt*1000);move(dt);for(Move m:moving){float ox=m.x,oy=m.y;m.t+=dt*m.speed;float z=(float)Math.sin(m.t)*m.range;if(m.axis==0)m.x=m.bx+z;else m.y=m.by+z;m.dx=m.x-ox;m.dy=m.y-oy;}for(Enemy e:enemies)e.tick(dt,this);Iterator<Shot>qi=shots.iterator();while(qi.hasNext()){Shot q=qi.next();q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=560*dt;q.life-=dt;if(q.life<0||q.x<cameraX-500||q.x>cameraX+getWidth()+700){qi.remove();continue;}if(hit(x,y,r,q.x,q.y,q.r)){respawn();qi.remove();break;}}for(Particle q:particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=500*dt;q.vx*=.985f;}particles.removeIf(a->a.life<=0);for(Gem g:gems)if(!g.got&&hit(x,y,r,g.x,g.y,g.r)){g.got=true;gemsThis++;gemsTotal++;save();burst(g.x,g.y,10,0xFFFFD166);audio.fx(Sfx.COIN,muted);}for(RectF q:springs)if(circleRect(x,y,r,q)&&vy>=0){y=q.top-r;vy=-1250;grounded=false;burst(x,y+r,12,0xFF7CE7FF);audio.fx(Sfx.SPRING,muted);}for(RectF q:spikes)if(circleRect(x,y,r,q)){respawn();break;}for(RectF q:checkpoints)if(q.right<1&&!q.contains(x,y)&&Math.abs(x-q.left)<44&&Math.abs(y-q.top)<100){q.right=1;checkpointX=q.left;checkpointY=q.top-58;burst(q.left,q.top-55,15,0xFF7DFFB2);audio.fx(Sfx.CHECK,muted);}if(bossAlive)boss(dt);if(x>worldW-210&&!bossAlive){won=true;ui=4;unlocked=Math.max(unlocked,Math.min(LEVEL_COUNT,level+1));save();audio.stop();audio.fx(Sfx.WIN,muted);burst(x,y,40,0xFFFFD166);}camera(dt);}
    private float checkpointX=270,checkpointY=650;
    private void move(float dt){if(left){vx-=1500*dt;facing=-1;}if(right){vx+=1500*dt;facing=1;}if(!left&&!right)vx*=Math.pow(.001,dt);vx=clamp(vx,-620,620);long now=SystemClock.uptimeMillis();if(jumpPressed){jumpAt=now;jumpPressed=false;}if(now-jumpAt<130&&(grounded||now-groundedAt<120)){vy=-980;jumpAt=0;grounded=false;burst(x,y+r,8,0xFFBBD9FF);audio.fx(Sfx.JUMP,muted);}if(!jumpHeld&&vy<-420)vy+=1500*dt;vy+=2420*dt;vy=clamp(vy,-1100,1350);float ox=x,oy=y;x+=vx*dt;y+=vy*dt;grounded=false;for(RectF q:blocks){if(!circleRect(x,y,r,q))continue;if(ox+r<=q.left&&x+r>q.left){x=q.left-r;vx=-Math.abs(vx)*.08f;}else if(ox-r>=q.right&&x-r<q.right){x=q.right+r;vx=Math.abs(vx)*.08f;}else if(oy+r<=q.top&&y+r>q.top){y=q.top-r;vy=0;grounded=true;groundedAt=now;}else if(oy-r>=q.bottom&&y-r<q.bottom){y=q.bottom+r;vy=Math.max(0,vy);}}for(Move m:moving)if(circleRect(x,y,r,new RectF(m.x,m.y,m.x+m.w,m.y+m.h))&&oy+r<=m.y+4&&y+r>=m.y){y=m.y-r;vy=0;grounded=true;groundedAt=now;x+=m.dx;y+=m.dy;}if(y>1300)respawn();}
    private void boss(float dt){if(bossHp<=0){bossAlive=false;return;}bossTimer+=dt;bossX+=(x-bossX)*Math.min(1,dt*1.5f);bossY=610+(float)Math.sin(bossTimer*2.1)*22;if(bossTimer>1.3){bossTimer=0;float dx=x-bossX,dy=y-bossY,len=(float)Math.sqrt(dx*dx+dy*dy)+.01f;shots.add(new Shot(bossX,bossY,dx/len*430,dy/len*430,14));audio.fx(Sfx.BOSS,muted);}if(hit(x,y,r,bossX,bossY,65)&&SystemClock.uptimeMillis()-bossHitAt>800){respawn();bossHitAt=SystemClock.uptimeMillis();}if(vy>0&&y+r<bossY+15&&y+r>bossY-40&&Math.abs(x-bossX)<72&&SystemClock.uptimeMillis()-bossHitAt>450){bossHp-=25;vy=-780;bossHitAt=SystemClock.uptimeMillis();burst(bossX,bossY,18,0xFFFFB347);audio.fx(Sfx.COIN,muted);}}
    private void respawn(){deaths++;x=checkpointX;y=checkpointY;vx=vy=0;shake=.5f;shots.clear();burst(x,y,14,0xFFFF6B6B);audio.fx(Sfx.HURT,muted);}
    private void camera(float dt){float tx=x-getWidth()*.34f,ty=y-getHeight()*.58f;cameraX+=(tx-cameraX)*Math.min(1,dt*5);cameraY+=(ty-cameraY)*Math.min(1,dt*5);cameraX=clamp(cameraX,0,Math.max(0,worldW-getWidth()));cameraY=clamp(cameraY,-100,420);shake*=.88f;}

    private void render(Canvas c){int w=getWidth(),h=getHeight();if(ui==0){menu(c,w,h);return;}if(ui==1){select(c,w,h);return;}if(ui==5){settings(c,w,h);return;}world(c,w,h);if(ui==3)pause(c,w,h);if(ui==4)win(c,w,h);}
    private void world(Canvas c,int w,int h){p.setShader(new LinearGradient(0,0,w,h,0xFF071225,0xFF1B6073,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);parallax(c,w,h,.13f,0xFF10324A,100);parallax(c,w,h,.25f,0xFF17485C,160);c.save();c.translate(-cameraX,-cameraY);if(shake>.01)c.translate((float)Math.sin(elapsed*.03)*shake*10,(float)Math.cos(elapsed*.02)*shake*10);for(RectF q:blocks)block(c,q);for(Move m:moving)platform(c,m);for(RectF q:springs)spring(c,q);for(RectF q:spikes)spike(c,q);for(Gem g:gems)if(!g.got)gem(c,g);for(RectF q:checkpoints)checkpoint(c,q);for(Enemy e:enemies)e.draw(c);for(Shot q:shots)shot(c,q);if(bossAlive)bossDraw(c);goal(c);for(Particle q:particles)part(c,q);ball(c);c.restore();hud(c,w,h);}
    private void parallax(Canvas c,int w,int h,float f,int color,int bh){p.setColor(color);Path z=new Path();float off=-(cameraX*f)%420;z.moveTo(0,h);for(int ix=-500;ix<w+700;ix+=140)z.lineTo(ix+off,h-bh-(float)Math.sin((ix+cameraX*f)*.012)*35);z.lineTo(w,h);z.close();c.drawPath(z,p);}
    private void block(Canvas c,RectF q){p.setColor(0xFF17374B);c.drawRoundRect(q,10,10,p);p.setColor(0xFF4C98A0);c.drawRoundRect(q.left,q.top,q.right,q.top+13,8,8,p);p.setColor(0xFF2B6173);c.drawRect(q.left+7,q.top+13,q.right-7,q.top+17,p);}
    private void platform(Canvas c,Move q){p.setColor(0xFF244F64);c.drawRoundRect(q.x,q.y,q.x+q.w,q.y+q.h,9,9,p);p.setColor(0xFF78D7D9);c.drawRoundRect(q.x+5,q.y+4,q.x+q.w-5,q.y+8,4,4,p);}
    private void spring(Canvas c,RectF q){p.setColor(0xFF2B3A50);c.drawRoundRect(q,8,8,p);p.setColor(0xFF7CE7FF);c.drawRoundRect(q.left+5,q.top+4,q.right-5,q.top+9,4,4,p);}
    private void spike(Canvas c,RectF q){p.setColor(0xFFFF6E72);Path z=new Path();z.moveTo(q.left,q.bottom);z.lineTo(q.centerX(),q.top);z.lineTo(q.right,q.bottom);z.close();c.drawPath(z,p);}
    private void gem(Canvas c,Gem g){float k=1+(float)Math.sin((elapsed+g.phase)*.006)*.1f;c.save();c.translate(g.x,g.y);c.scale(k,k);p.setShadowLayer(15,0,0,0x66FFD166);p.setColor(0xFFFFD166);Path z=new Path();z.moveTo(0,-g.r);z.lineTo(g.r*.8f,0);z.lineTo(0,g.r);z.lineTo(-g.r*.8f,0);z.close();c.drawPath(z,p);p.clearShadowLayer();p.setColor(0xFFFFF1B0);c.drawCircle(-5,-6,3,p);c.restore();}
    private void checkpoint(Canvas c,RectF q){p.setColor(0xFFBCECF0);c.drawRect(q.left,q.top-70,q.left+4,q.top,p);p.setColor(q.right>0?0xFF7DFFB2:0xFF8198AA);Path z=new Path();z.moveTo(q.left+4,q.top-70);z.lineTo(q.left+50,q.top-54);z.lineTo(q.left+4,q.top-38);z.close();c.drawPath(z,p);}
    private void goal(Canvas c){p.setShadowLayer(20,0,0,0x887DFFB2);p.setColor(0xFF7DFFB2);c.drawCircle(worldW-110,650,38,p);p.clearShadowLayer();p.setColor(0xFF0B1624);c.drawCircle(worldW-110,650,22,p);}
    private void ball(Canvas c){c.save();c.translate(x,y);p.setShader(new RadialGradient(-10,-12,42,new int[]{Color.WHITE,0xFFE5F4FF,0xFF3B93D0,0xFF11517F},new float[]{0,.08f,.62f,1},Shader.TileMode.CLAMP));p.setShadowLayer(18,0,12,0x88000000);c.drawCircle(0,0,r,p);p.clearShadowLayer();p.setShader(null);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(5);p.setColor(0xFFB8E3FF);c.drawArc(-r+5,-r+5,r-5,r-5,rotation(vx),150,false,p);p.setStyle(Paint.Style.FILL);c.drawCircle(-10,-11,7,white());c.restore();}
    private Paint white(){p.setColor(0xFFF9FDFF);return p;} private float rotation(float a){return a*12;}
    private void part(Canvas c,Particle q){p.setAlpha((int)(255*Math.max(0,q.life/q.max)));p.setColor(q.color);c.drawCircle(q.x,q.y,q.size,p);p.setAlpha(255);}
    private void shot(Canvas c,Shot q){p.setShadowLayer(12,0,0,0x88FF7043);p.setColor(0xFFFF7043);c.drawCircle(q.x,q.y,q.r,p);p.clearShadowLayer();}
    private void bossDraw(Canvas c){p.setShadowLayer(25,0,8,0xAAFF4F5A);p.setColor(0xFF8E3A54);c.drawCircle(bossX,bossY,65,p);p.clearShadowLayer();p.setColor(0xFFFFB347);c.drawCircle(bossX-18,bossY-8,10,p);c.drawCircle(bossX+18,bossY-8,10,p);p.setColor(0xFF2D1532);c.drawCircle(bossX-18,bossY-8,4,p);c.drawCircle(bossX+18,bossY-8,4,p);p.setColor(0xFF1A2130);c.drawRect(bossX-80,bossY-96,bossX+80,bossY-82,p);p.setColor(0xFF7DFFB2);c.drawRect(bossX-78,bossY-94,bossX-78+156*(bossHp/bossMaxHp),bossY-85,p);}
    private void hud(Canvas c,int w,int h){p.setColor(0xAA071225);c.drawRoundRect(18,16,310,66,18,18,p);p.setColor(Color.WHITE);p.setTextSize(21);p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText("LEVEL "+level+"   GEM "+gemsThis,34,48,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(16);c.drawText(time(elapsed),240,48,p);button(c,w-70,42,56,48,"Ⅱ",0x553A5877);float cy=h-92;button(c,78,cy,66,56,"‹",0x553A5877);button(c,160,cy,66,56,"›",0x553A5877);button(c,w-88,cy,76,56,"↑",0x557DFFB2);}
    private void menu(Canvas c,int w,int h){p.setShader(new LinearGradient(0,0,w,h,0xFF071225,0xFF16445F,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,p);p.setShader(null);float cx=w*.5f,cy=h*.32f;logoBall(c,cx,cy,76);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setColor(Color.WHITE);p.setTextSize(44);c.drawText("BALL",cx,cy+132,p);p.setColor(0xFF7CE7FF);p.setTextSize(38);c.drawText("PLATFORMER",cx,cy+174,p);button(c,cx,cy+255,260,62,"PLAY",0xAA2D76A3);button(c,cx,cy+330,260,58,"LEVEL SELECT",0x553A5877);button(c,cx+155,cy+330,80,58,"⚙",0x553A5877);p.setTypeface(Typeface.DEFAULT);p.setTextSize(13);p.setColor(0x99FFFFFF);c.drawText("24 levels • checkpoints • bosses • mobile controls",cx,h-24,p);p.setTextAlign(Paint.Align.LEFT);}
    private void logoBall(Canvas c,float x,float y,float r){p.setShader(new RadialGradient(x-18,y-22,r,new int[]{Color.WHITE,0xFFBFE9FF,0xFF4A9DD7,0xFF0E4771},new float[]{0,.1f,.64f,1},Shader.TileMode.CLAMP));c.drawCircle(x,y,r,p);p.setShader(null);p.setColor(0xFF193B55);c.drawCircle(x-18,y-20,9,p);c.drawCircle(x+18,y-20,9,p);}
    private void select(Canvas c,int w,int h){p.setColor(0xFF081526);c.drawRect(0,0,w,h,p);p.setColor(Color.WHITE);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(34);c.drawText("SELECT LEVEL",30,52,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(16);p.setColor(0xAAFFFFFF);c.drawText("Unlocked: "+unlocked+" / "+LEVEL_COUNT,32,78,p);float gx=w/6.5f;for(int i=1;i<=LEVEL_COUNT;i++){int rr=(i-1)/6,cc=(i-1)%6;float px=70+cc*gx,py=125+rr*82;p.setColor(i<=unlocked?0xFF22536A:0xFF26313F);c.drawRoundRect(px-44,py-25,px+44,py+25,14,14,p);p.setTextAlign(Paint.Align.CENTER);p.setColor(i<=unlocked?0xFF7CE7FF:0xFF78818B);p.setTextSize(22);c.drawText(""+i,px,py+8,p);}p.setTextAlign(Paint.Align.LEFT);button(c,w-76,h-46,105,56,"BACK",0x553A5877);}
    private void pause(Canvas c,int w,int h){overlay(c);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(42);p.setColor(Color.WHITE);c.drawText("PAUSED",w/2f,h*.28f,p);button(c,w/2f,h*.50f,220,58,"RESUME",0xAA2D76A3);button(c,w/2f,h*.63f,220,58,"RESTART",0x553A5877);button(c,w/2f,h*.76f,220,58,"LEVEL SELECT",0x553A5877);p.setTextAlign(Paint.Align.LEFT);}
    private void win(Canvas c,int w,int h){overlay(c);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(44);p.setColor(0xFFFFD166);c.drawText(level==LEVEL_COUNT?"WORLD COMPLETE!":"LEVEL COMPLETE!",w/2f,h*.28f,p);p.setColor(Color.WHITE);p.setTypeface(Typeface.DEFAULT);p.setTextSize(20);c.drawText("Time  "+time(elapsed),w/2f,h*.38f,p);c.drawText("Gems  "+gemsThis,w/2f,h*.45f,p);button(c,w/2f,h*.59f,250,60,level<LEVEL_COUNT?"NEXT LEVEL":"PLAY AGAIN",0xAA2D76A3);button(c,w/2f,h*.72f,250,56,"LEVEL SELECT",0x553A5877);p.setTextAlign(Paint.Align.LEFT);}
    private void settings(Canvas c,int w,int h){p.setColor(0xFF081526);c.drawRect(0,0,w,h,p);p.setColor(Color.WHITE);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(38);c.drawText("SETTINGS",32,62,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(20);c.drawText("Sound",40,140,p);button(c,220,130,150,52,muted?"OFF":"ON",muted?0x553A5877:0xAA2D76A3);c.drawText("Unlocked levels: "+unlocked,40,225,p);c.drawText("Lifetime gems: "+gemsTotal,40,260,p);button(c,230,340,210,56,"BACK",0x553A5877);}
    private void overlay(Canvas c){p.setColor(0xAA050B13);c.drawRect(0,0,getWidth(),getHeight(),p);}
    private void button(Canvas c,float x,float y,float w,float h,String t,int col){p.setColor(col);c.drawRoundRect(x-w/2,y-h/2,x+w/2,y+h/2,18,18,p);s.setColor(0x66FFFFFF);s.setStrokeWidth(2);c.drawRoundRect(x-w/2,y-h/2,x+w/2,y+h/2,18,18,s);p.setColor(Color.WHITE);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setTextSize(h*.38f);c.drawText(t,x,y+h*.13f,p);p.setTextAlign(Paint.Align.LEFT);}
    private static boolean circleRect(float cx,float cy,float r,RectF q){float nx=clamp(cx,q.left,q.right),ny=clamp(cy,q.top,q.bottom),dx=cx-nx,dy=cy-ny;return dx*dx+dy*dy<=r*r;}
    private static boolean hit(float ax,float ay,float ar,float bx,float by,float br){float dx=ax-bx,dy=ay-by,rr=ar+br;return dx*dx+dy*dy<=rr*rr;}
    private static float clamp(float v,float a,float b){return Math.max(a,Math.min(b,v));}
    private static String time(long ms){return String.format(Locale.US,"%02d:%02d",(ms/1000)/60,(ms/1000)%60);}
    private void burst(float px,float py,int n,int color){for(int i=0;i<n;i++){double a=rng.nextDouble()*Math.PI*2;float sp=50+rng.nextFloat()*290;particles.add(new Particle(px,py,(float)Math.cos(a)*sp,(float)Math.sin(a)*sp-50,2+rng.nextFloat()*5,color,.35f+rng.nextFloat()*.55f));}}
    private void save(){prefs.edit().putInt("unlocked",unlocked).putInt("gems",gemsTotal).putBoolean("muted",muted).apply();}

    @Override public boolean onTouchEvent(MotionEvent e){float tx=e.getX(),ty=e.getY();if(ui==0&&e.getAction()==MotionEvent.ACTION_UP){float cy=getHeight()*.32f;if(hit2(tx,ty,getWidth()/2f,cy+255,280,72)){startLevel(unlocked);return true;}if(hit2(tx,ty,getWidth()/2f,cy+330,280,68)){ui=1;return true;}if(hit2(tx,ty,getWidth()/2f+155,cy+330,90,70)){ui=5;return true;}return true;}if(ui==1&&e.getAction()==MotionEvent.ACTION_UP){float gx=getWidth()/6.5f;for(int i=1;i<=LEVEL_COUNT;i++){int rr=(i-1)/6,cc=(i-1)%6;float px=70+cc*gx,py=125+rr*82;if(i<=unlocked&&hit2(tx,ty,px,py,95,60)){startLevel(i);return true;}}if(hit2(tx,ty,getWidth()-76,getHeight()-46,125,70)){ui=0;return true;}return true;}if(ui==5&&e.getAction()==MotionEvent.ACTION_UP){if(hit2(tx,ty,220,130,180,70)){muted=!muted;save();return true;}if(hit2(tx,ty,230,340,250,70)){ui=0;return true;}return true;}if(ui==3&&e.getAction()==MotionEvent.ACTION_UP){if(hit2(tx,ty,getWidth()/2f,getHeight()*.50f,250,72)){ui=2;audio.music(level,muted);return true;}if(hit2(tx,ty,getWidth()/2f,getHeight()*.63f,250,72)){startLevel(level);return true;}if(hit2(tx,ty,getWidth()/2f,getHeight()*.76f,250,72)){ui=1;audio.stop();return true;}return true;}if(ui==4&&e.getAction()==MotionEvent.ACTION_UP){if(hit2(tx,ty,getWidth()/2f,getHeight()*.59f,260,72)){startLevel(level<LEVEL_COUNT?level+1:1);return true;}if(hit2(tx,ty,getWidth()/2f,getHeight()*.72f,260,68)){ui=1;return true;}return true;}if(ty<90&&tx>getWidth()-125&&e.getAction()==MotionEvent.ACTION_UP){ui=3;audio.stop();return true;}if(ui==2){int a=e.getActionMasked();boolean down=a==MotionEvent.ACTION_DOWN||a==MotionEvent.ACTION_MOVE||a==MotionEvent.ACTION_POINTER_DOWN;boolean up=a==MotionEvent.ACTION_UP||a==MotionEvent.ACTION_CANCEL||a==MotionEvent.ACTION_POINTER_UP;if(ty>getHeight()-170){if(tx<125)left=down;if(tx<260&&tx>=125)right=down;if(tx>getWidth()-165){if(down)jumpPressed=true;jumpHeld=down;}if(up&&tx<125)left=false;if(up&&tx>=125&&tx<260)right=false;if(up&&tx>getWidth()-165)jumpHeld=false;return true;}}return true;}
    private boolean hit2(float x,float y,float cx,float cy,float w,float h){return Math.abs(x-cx)<=w/2&&Math.abs(y-cy)<=h/2;}

    static final class Gem{float x,y,r=17,phase;boolean got;Gem(float x,float y,float phase){this.x=x;this.y=y;this.phase=phase;}}
    static final class Particle{float x,y,vx,vy,size,life,max;int color;Particle(float x,float y,float vx,float vy,float size,int color,float life){this.x=x;this.y=y;this.vx=vx;this.vy=vy;this.size=size;this.color=color;this.life=life;this.max=life;}}
    static final class Shot{float x,y,vx,vy,r,life=5;Shot(float x,float y,float vx,float vy,float r){this.x=x;this.y=y;this.vx=vx;this.vy=vy;this.r=r;}}
    static final class Move{float bx,by,x,y,w,h,range,speed,t,dx,dy;int axis;Move(float x,float y,float w,float h,float range,float speed,int axis){bx=this.x=x;by=this.y=y;this.w=w;this.h=h;this.range=range;this.speed=speed;this.axis=axis;}}
    static final class Enemy{float x,y,base,min,max,speed=100,t;int type,dir=1;long hitAt;Enemy(float x,float y,int t){this.x=x;this.y=y;base=y;this.type=t;min=x-110;max=x+110;}void tick(float dt,GameView g){t+=dt;if(type==0){x+=dir*speed*dt;if(x<min||x>max)dir*=-1;}else if(type==1){x+=(float)Math.sin(t*2.7)*speed*.5f*dt;y=base+(float)Math.sin(t*3)*45;}else{x+=dir*speed*dt;y=base-(float)Math.abs(Math.sin(t*3))*35;if(x<min||x>max)dir*=-1;}if(hit(g.x,g.y,g.r,x,y,26)&&SystemClock.uptimeMillis()-hitAt>650){g.respawn();hitAt=SystemClock.uptimeMillis();}}void draw(Canvas c){p.setColor(type==0?0xFFFF6B6B:type==1?0xFF9E8CFF:0xFFFF9D4D);c.drawCircle(x,y,26,p);p.setColor(Color.WHITE);c.drawCircle(x-7,y-5,4,p);c.drawCircle(x+7,y-5,4,p);p.setColor(0xFF1B2230);c.drawCircle(x-7+dir*2,y-5,2,p);c.drawCircle(x+7+dir*2,y-5,2,p);}}
    static final class LevelFactory{static void make(GameView g,int lv){int world=(lv-1)/4,var=(lv-1)%4;g.worldW=5200+world*280;float xx=0;for(int i=0;i<12+world;i++){float ww=430+((i*73+lv*19)%260);float yy=780-(i%3)*65;g.blocks.add(new RectF(xx,yy,xx+ww,yy+115));if(i%2==1)g.gems.add(new Gem(xx+ww*.48f,yy-72,i*41));if(i%3==2)g.spikes.add(new RectF(xx+ww*.65f,yy-25,xx+ww*.65f+45,yy+18));xx+=ww+95+((i*31+lv*7)%80);}while(xx<g.worldW-450){g.blocks.add(new RectF(xx,820,500,110));if(((int)xx)%2==0)g.springs.add(new RectF(xx+190,788,260,820));xx+=590;}for(int i=0;i<9;i++){float px=520+i*470+var*35,py=580-(i%3)*45;g.moving.add(new Move(px,py,145,25,55+(i%3)*35,.9f+(i%2)*.25f,i%2));}for(int i=0;i<8;i++){Enemy e=new Enemy(760+i*560,715-(i%2)*125,(i+var)%3);e.speed=95+(lv%5)*9;g.enemies.add(e);}for(int i=0;i<20;i++)g.gems.add(new Gem(360+i*250,600-(i%3)*45,(i*67+lv*11)%360));for(int i=0;i<5;i++)g.checkpoints.add(new RectF(1200+i*820,570,1204+i*820,590));if(var==1||var==3)for(int i=0;i<5;i++)g.spikes.add(new RectF(1100+i*700,470+(i%2)*170,1145+i*700,520+(i%2)*170));if(var==2)for(int i=0;i<5;i++)g.springs.add(new RectF(1050+i*780,790,1120+i*780,822));if(lv%4==0){g.bossAlive=true;g.bossX=g.worldW-700;g.bossY=610;g.bossMaxHp=100+world*25;g.bossHp=g.bossMaxHp;}g.blocks.add(new RectF(g.worldW-540,560,g.worldW-260,600));g.blocks.add(new RectF(g.worldW-260,680,g.worldW,900));}}
    static final class Sfx{static final int JUMP=1,COIN=2,HURT=3,WIN=4,SPRING=5,CHECK=6,BOSS=7;final int rate=22050;Thread musicThread;volatile boolean run;void fx(int t,boolean mute){if(mute)return;float f=t==JUMP?660:t==COIN?960:t==HURT?180:t==WIN?780:t==SPRING?520:t==CHECK?880:240;float d=t==WIN?.45f:.12f;new Thread(()->tone(f,d,t==HURT?.22f:.17f)).start();}void tone(float f,float d,float vol){int n=(int)(rate*d);short[] a=new short[n];for(int i=0;i<n;i++){float z=i/(float)rate,env=Math.min(1,z*30)*Math.min(1,(d-z)*16);a[i]=(short)(Math.sin(6.28318*f*z)*32767*vol*env);}AudioTrack q=new AudioTrack(AudioManager.STREAM_MUSIC,rate,AudioFormat.CHANNEL_OUT_MONO,AudioFormat.ENCODING_PCM_16BIT,n*2,AudioTrack.MODE_STATIC);q.write(a,0,a.length);q.play();try{Thread.sleep((long)(d*1000)+20);}catch(Exception ignored){}q.release();}void music(int lv,boolean mute){stop();if(mute)return;run=true;musicThread=new Thread(()->{float[] ns={261.6f,329.6f,392f,523.3f,392f,329.6f,293.7f,349.2f};while(run)for(float f:ns){if(!run)break;tone(f,.13f,.035f);}});musicThread.start();}void stop(){run=false;if(musicThread!=null)musicThread.interrupt();musicThread=null;}}
}
